INSERT INTO `star-wars`.`droid_fight_data` (`fight_intensity`, `damage_done`, `droid_id`, `last_fought_by`) VALUES ('7.9', '79', '7', '12');
INSERT INTO `star-wars`.`droid_fight_data` (`fight_intensity`, `damage_done`, `droid_id`, `last_fought_by`) VALUES ('5.3', '53', '10', '12');
INSERT INTO `star-wars`.`droid_fight_data` (`fight_intensity`, `damage_done`, `droid_id`, `last_fought_by`) VALUES ('6.1', '61', '4', '12');
INSERT INTO `star-wars`.`droid_fight_data` (`fight_intensity`, `damage_done`, `droid_id`, `last_fought_by`) VALUES ('1.1', '11', '3', '12');
INSERT INTO `star-wars`.`droid_fight_data` (`fight_intensity`, `damage_done`, `droid_id`, `last_fought_by`) VALUES ('3.7', '37', '14', '12');
INSERT INTO `star-wars`.`droid_fight_data` (`fight_intensity`, `damage_done`, `droid_id`, `last_fought_by`) VALUES ('3.5', '35', '17', '12');
INSERT INTO `star-wars`.`droid_fight_data` (`fight_intensity`, `damage_done`, `droid_id`, `last_fought_by`) VALUES ('2.8', '28', '11', '12');
INSERT INTO `star-wars`.`droid_fight_data` (`fight_intensity`, `damage_done`, `droid_id`, `last_fought_by`) VALUES ('3.9', '39', '13', '12');
INSERT INTO `star-wars`.`droid_fight_data` (`fight_intensity`, `damage_done`, `droid_id`, `last_fought_by`) VALUES ('1.4', '14', '2', '12');
